### ISSUE TITLE
Can't be uploaded to dedicated server

### ISSUE THREAD

**Issue by Tschensen** [AmonFlorian/FS22_BaNe#3]
The server always returned: "file is broken". I've tried to re-zip the file, but it stays broken for a dedicated server.

**Comment by AmonFlorian** [comment]
No multiplayer-support as of current version (v1.x).

Check back later.

**Comment by Tschensen** [comment]
Thank you for answer. If you need any assistance in QA, just let me know.

**Comment by AmonFlorian** [comment]
Would be glad to get help :) You got discord?

**Comment by Tschensen** [comment]
Yes, sure.

**Comment by AmonFlorian** [comment]
Don't mind adding me: kwaam#7342
